### ISSUE TITLE
Missing Grafana plugins and dashboard errors

### ISSUE THREAD

**Issue by Strum355** [butlerx/metric-log-demo#1]
`Panel plugin not found: stat` and `r is not a function` after having run the `docker-compose` command. Also no results from Loki in Explore tab
![image](https://user-images.githubusercontent.com/18282288/75627882-fbd8ce80-5bcb-11ea-922f-22301f617a3e.png)

**Comment by butlerx** [comment]
You appear to have the wrong version of grafana pulled. Try tunning ```
docker-compose pull
Docker-compose up -d
``` 
And for loki did you install the loki logs driver as mentioned in the readme

**Comment by Strum355** [comment]
Loki plugin was installed. Ill try pulling latest grafana image when im back at laptop
